# Generated by Django 3.2 on 2021-05-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210504_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='zanr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='web.zanr'),
            preserve_default=False,
        ),
    ]
