# Generated by Django 3.2 on 2021-05-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_film_zanr'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='film/%Y/%m/%d/', verbose_name='Fotka filmu'),
        ),
    ]
