# Generated by Django 3.2 on 2021-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_film_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rezie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Režie'),
        ),
        migrations.AddField(
            model_name='film',
            name='scenar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Scénář'),
        ),
        migrations.AlterField(
            model_name='film',
            name='stat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Stát'),
        ),
    ]
