# Generated by Django 3.2 on 2021-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210504_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rezie',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Režie'),
        ),
        migrations.AlterField(
            model_name='film',
            name='scenar',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Scénář'),
        ),
        migrations.AlterField(
            model_name='film',
            name='stat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stát'),
        ),
    ]
